# Generated by Chocoleotey. https://github.com/leobastiani/chocoleotey

$ErrorActionPreference = 'Stop';
$toolsDir = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"

Install-BinFile -Name 'hide' -Path (Join-Path (Join-Path $toolsDir 'bin') 'hide.bat')
Install-BinFile -Name 'show' -Path (Join-Path (Join-Path $toolsDir 'bin') 'show.bat')
